name: Label sponsors
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  build:
    name: is-sponsor-label
    runs-on: ubuntu-latest
    steps:
      - uses: rix1337/is-sponsor-label-action@v1
        with:
          sponsor_label: sponsor ❤️
          not_sponsor_label: creator is no sponsor 😔
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
